def PASSWORD = sh(script: 'tr -dc A-Za-z0-9 </dev/urandom | head -c 13; echo', returnStdout: true).trim()
pipeline {
    agent any
    parameters {
        string(name: 'LOGIN', defaultValue: '', description: 'Unique user identifier. Usually name and lastname')

        string(name: 'NAME_LASTNAME', defaultValue: '', description: 'User Name and Lastname')

        choice(name: 'GROUP_DEPARTMENT', choices: ['Contabilidad', 'Finanzas', 'Tecnologia'], description: '')
    }
    stages {
        stage('Create User') {
            steps {
                script{
                    echo "Creating user with temporal password for ${params.NAME_LASTNAME}"
                    sudo useradd -m ${params.LOGIN}
                }
            }
        }
        stage('Add Password') {
            steps {
                script{
                    echo ${PASSWORD} | sudo passwd ${params.LOGIN} --stding
                    echo "Password created: ${PASSWORD}"
                }
            }
        }
        stage('Add Group') {
            steps {
                script{
                    sudo usermod -aG ${params.GROUP_DEPARTMENT} ${params.LOGIN}
                    echo "Group added: ${GROUP_DEPARTMENT}"
                }
            }
        }
    }
}

